// <auto-generated />
using System;
using DojoKitaoApp.Libraries.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DojoKitaoApp.Libraries.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240716182250_CreateTreinosAulas")]
    partial class CreateTreinosAulas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DojoKitaoApp.Libraries.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("DojoKitaoApp.Libraries.Domain.Entities.Aula", b =>
                {
                    b.Property<int>("TreinoId")
                        .HasColumnType("int");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("TreinoId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("DojoKitaoApp.Libraries.Domain.Entities.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArteMarcial")
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("DojoKitaoApp.Libraries.Domain.Entities.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArteMarcial")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("DojoKitaoApp.Libraries.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("DojoKitaoApp.Libraries.Domain.Entities.Matricula", "Matricula")
                        .WithOne("Aluno")
                        .HasForeignKey("DojoKitaoApp.Libraries.Domain.Entities.Aluno", "MatriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("DojoKitaoApp.Libraries.Domain.Entities.Aula", b =>
                {
                    b.HasOne("DojoKitaoApp.Libraries.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Aulas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DojoKitaoApp.Libraries.Domain.Entities.Treino", "Treino")
                        .WithMany("Aulas")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("DojoKitaoApp.Libraries.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("DojoKitaoApp.Libraries.Domain.Entities.Matricula", b =>
                {
                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("DojoKitaoApp.Libraries.Domain.Entities.Treino", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
